name: Build & Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read and bump version
        id: versioning
        run: |
          VERSION_FILE=version.txt
          VERSION=$(cat $VERSION_FILE)
          echo "Current version: $VERSION"

          # Remove "v" and split version into parts
          BASE_VERSION=${VERSION#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$BASE_VERSION"

          # Bump PATCH version
          PATCH=$((PATCH + 1))
          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"

          echo "New version: $NEW_VERSION"
          echo "$NEW_VERSION" > $VERSION_FILE

          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit updated version
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add version.txt
          git commit -m "Bump version to $VERSION"
          git push

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/mini-fullstack-app:latest
            ${{ secrets.DOCKER_USERNAME }}/mini-fullstack-app:${{ env.VERSION }}
